build:
  image: node:argon
  commands:
    - echo "ok"
publish:
  ecr:
    access_key: $$DRONE_CI_ACCESS_KEY
    secret_key: $$DRONE_CI_SECRET_KEY
    region: us-west-2
    repo: lab-test
    tag: latest
    storage_driver: aufs
  ecs:
    access_key: $$DRONE_CI_ACCESS_KEY
    secret_key: $$DRONE_CI_SECRET_KEY
    region: us-west-2
    family: dummy-service-task
    image_name: lab-test
    image_tag: latest
    service: test-svc
    port_mappings:
      - 3000 9000
    memory: 128
    cluster: lab-test
