build:
  image: node:argon
  commands:
    - echo "ok"
publish:
  ecr:
    access_key: $$DRONE_CI_ACCESS_KEY
    secret_key: $$DRONE_CI_SECRET_KEY
    region: us-west-2
    repo: lab-test
    tag: latest
    storage_driver: aufs
